- name: variables from inventory
  hosts: local
  connection: local
  tasks:
  - name: print variables from inventory
    ansible.builtin.debug:
      msg: "Trainer is {{trainer}}, course is: {{course}}"

